#!/bin/bash
# 
# 脚本名称：test_window_chrome.sh
# 职责：测试自定义窗口 chrome 功能的手动验证指南
# 用法：在 Windows 环境中构建并运行应用后使用此指南进行验证

echo "=== WinWindowChrome 自定义窗口框架测试指南 ==="
echo ""
echo "此脚本提供手动测试自定义窗口 chrome 功能的指导。"
echo ""
echo "修复内容："
echo "1. DwmExtendFrameIntoClientArea 边距从 {0,0,0,0} 修改为 {1,1,1,1}"
echo "2. 移除默认标题栏 (WS_CAPTION) 但保留其他窗口功能"
echo "3. 正确处理 WM_NCACTIVATE 消息以支持自定义激活绘制"
echo ""
echo "预期效果："
echo "- 窗口应该没有默认的 Windows 标题栏"
echo "- 应用的自定义标题栏应该可以正常绘制和交互"
echo "- 窗口边框和阴影应该保持正常"
echo "- 拖拽、调整大小、最小化/最大化功能应该正常工作"
echo "- 任务栏集成应该正常（Alt+Tab、任务栏按钮等）"
echo ""
echo "测试步骤："
echo "1. 构建并启动 Fangjia 应用"
echo "2. 检查窗口是否显示自定义标题栏而不是系统默认标题栏"
echo "3. 测试拖拽标题栏区域移动窗口"
echo "4. 测试窗口边框调整大小"
echo "5. 测试最小化/最大化按钮"
echo "6. 检查窗口阴影是否正常显示"
echo "7. 使用 Alt+Tab 检查任务栏集成"
echo ""
echo "如果测试失败，可能的原因："
echo "- Qt6 版本不支持此功能"
echo "- Windows 版本不支持 DWM 扩展"
echo "- 其他 Qt 窗口设置与自定义 chrome 冲突"
echo ""
echo "调试信息："
echo "- 检查控制台输出中的 'Attaching WinWindowChrome...' 消息"
echo "- 查看是否有 DWM 相关的错误消息"
echo "- 确认 WinWindowChrome::attach 返回非空指针"