name: CI Build

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-windows:
    runs-on: windows-2022
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Qt6
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.6.3'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'    # 原来为 win64_msvc2022_64
        modules: 'qtsvg qttools'
        cache: true
        
    - name: Setup MSVC
      uses: microsoft/setup-msbuild@v1
      
    - name: Configure CMake
      shell: bash
      run: |
        cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 17 2022" -A x64 -DCMAKE_PREFIX_PATH="${QT_ROOT_DIR}"
        
    - name: Build
      shell: bash
      run: |
        cmake --build build --config Release -- -m
        
    - name: Run tests
      shell: bash
      run: |
        ctest -C Release --test-dir build --output-on-failure
        
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Qt6
      run: |
        sudo apt-get update
        sudo apt-get install -y qt6-base-dev qt6-tools-dev libqt6opengl6-dev libqt6svg6-dev cmake build-essential
        
    - name: Configure CMake
      run: |
        cmake -B build -S . -DCMAKE_BUILD_TYPE=Release
        
    - name: Build
      run: |
        cmake --build build --parallel
        
    - name: Run tests
      run: |
        cd build
        ./tests/FangJia_Tests
